nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    # Ensure the read and write access
    privileged: true
    volumes:
      - ./site/:/var/www/html/:rw
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/nginx/:rw
    links:
      - php53:fpm53
      - php72:fpm72

php53:
      build: ./php/php53/
      expose:
          - "9000"
      privileged: true
      volumes:
          - ./site/:/var/www/html:rw
          - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
          - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
          - ./log/php-fpm/:/var/log/php-fpm/:rw
          - ./tmp:/var/lib/php/session
      links:
          - mysql:mysql

php72:
      build: ./php/php72/
      expose:
          - "9000"
      privileged: true
      volumes:
          - ./site/:/var/www/html/:rw
          - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
          - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
          - ./log/php-fpm/:/var/log/php-fpm/:rw
          - ./tmp:/var/lib/php/session
      links:
          - mysql:mysql

mysql:
      image: mysql:latest
      ports:
          - "3306:3306"
      privileged: true
      volumes:
          - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
          - ./mysql/:/var/lib/mysql/:rw
          - ./log/mysql/:/var/log/mysql/:rw
      environment:
          MYSQL_ROOT_PASSWORD: "1234567"
